apiVersion: v1
kind: Service
metadata:
  name: nginx-helm-app-service
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
  selector:
    app: nginx-pod
