kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: test
roleRef:
  kind: Role
  name: test-role
  apiGroup: rbac.authorization.k8s.io

