apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: test-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: test-secretstore
    kind: SecretStore
  target:
    name: test-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: /infra-handson/username
  - secretKey: password
    remoteRef:
      key: /infra-handson/password
