apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: test-secretstore
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awsssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awsssm-secret
            key: secret-access-key
